### ISSUE TITLE
Crashes game on handling long character names with accented letters

### ISSUE THREAD

**Issue by DioVento** [RaidcoreGG/GW2-CommandersToolkit#19]
I have a really bizarre bug to report, and my static spent about an hour and a half isolating it. The bug was causing me to hardcrash with no error log every time i zoned into a map. I thought at first it was the aerodrome, but it happened in the raid wing too. Long story short, it turns out it was one of our member's specific character - whenever i shared a map with this character, even at other sides of a giant open world map, my game hardcrashed immediately. I disabled all addons, testing one by one, and found that it was Squad Manager that caused it.

The character's name was "Glint Sez Gäy Rites". Other max-length names or names with the ä did not cause a crash, but consistently this character did. Said player then used an empty character slot to make another max-length name that had an umlaut character, which did cause a crash.

So there's probably something wonky with how your addon interprets accented characters in names.

**Comment by DeltaRaidcore** [comment]
https://github.com/RaidcoreGG/GW2-CommandersToolkit/releases/tag/20220918-135925 @DioVento
