### ISSUE TITLE
Improvement: Add notes textbox for subgroups

### ISSUE THREAD

**Issue by Linkaaaaa** [RaidcoreGG/GW2-CommandersToolkit#2]
Could be used for notes such as "party 1 goes left and party 2 goes right" for largos, "party 1 goes protection party 2 goes stability" for qadim, etc.

**Comment by DeltaRaidcore** [comment]
I need to think about how to implement that sine the note field is used for warnings (e.g > 5 players in sub).
Any suggestions?
